services:
  trainer:
    build:
      context: .
    image: pampas-trainer:latest
    env_file:
      - .env
    volumes:
      - ${DATA_ROOT}:/data         # onde estão as imagens + labels
      - ${OUTPUT_ROOT}:/out        # onde guardar os pesos
    command: []
